GET http://localhost:8000/user

###
GET http://localhost:8000/user/alvin9840@gmail.com

###
POST http://localhost:8000/user
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@gmail.com",
  "image": "Test Image"
}



###
GET http://localhost:8000/post

###
POST http://localhost:8000/post
Content-Type: application/json

# {
#   "postText":"Sample Post Msg",
#   "createdAt":"326347347",
#   "createdBy":"68d073c216a35fee5f0b4d77",
#   "imageUrl":"SampleUrl"
# }

###
PUT http://localhost:8000/post/like/68d20ecbeca1da1b646b8399
Content-Type: application/json

{
  "userId": "68d073c216a35fee5f0b4d77",
  "isLike": true
}